### ISSUE TITLE
implement marker for unread channels

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#10]
@karissa I'd like to implement this feature! This is the first time I've worked with React within an Electron app so please bear with me! 😄 

For the UI I imagine a little count next to the channel name when there are unread messages.

How would you suggest position of the last read message of a channel be stored? Saving to a json file or just localstorage? Or should it be saved to hyperdb to let everyone know read status? 😬

**Comment by noffle** [comment]
A lot of this kind of data would fit really well into a generic client module, like https://github.com/cabal-club/cabal-client. The idea is you pass in a leveldb (fs on electron + cli, maybe indexeddb on some future browser version) and it stores all non-p2p state (rea-d-up-to, preferences, etc) locally.

**Comment by nikolaiwarner** [comment]
I'm down for anything! 😄 I'll keep it simple for now and write to the settings file. Then maybe use cabal-client someday when it's ready.

@karissa Will #9 be landing soon?

**Comment by nikolaiwarner** [comment]
A first iteration of this feature is currently in. Let's utilize cabal-client in the future to handle this when that's an option.
