### ISSUE TITLE
Can't connect?

### ISSUE THREAD

**Issue by April93** [cabal-club/cabal-desktop#105]
The desktop app just seems to not work. I can run it, create a cabal, chat in it, etc. but it just never connects to anyone else. I tried the cli and it seemed to work, but I've got no idea how to use it.

**Comment by cblgh** [comment]
@April93 hey! yeah, that desktop client has some issues we're still working on. 

however, @nikolaiwarner just released a new desktop client which might work better for you! [see the release page](https://github.com/nikolaiwarner/cabal-desktop-mini/releases)

![](https://github.com/nikolaiwarner/cabal-desktop-mini/raw/master/screenshot.png)

**Comment by April93** [comment]
Yeah the mini client is working. Thanks! :D
