### ISSUE TITLE
App uses deprecated electron API

### ISSUE THREAD

**Issue by brortao** [cabal-club/cabal-desktop#108]
`(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.`

It's from this snippet:
```
const quit = app.makeSingleInstance(() => {
  if (!win) return
  if (win.isMinimized()) win.restore()
  win.focus()
})

if (quit) app.quit()
```

I wanted to move this to `app.requestSingleInstanceLock()` instead, but I'm not familiar enough with electron to know what this code actually does (API docs for `makeSingleInstance` seem to have disappeared from the internet...)! So I'm opening an issue to track it :)

**Comment by todrobbins** [comment]
@nikolaiwarner your thoughts? I'm also no Electron pro.

**Comment by nikolaiwarner** [comment]
@brortao You should be safe to replace that with something like:
```
app.requestSingleInstanceLock()
app.on('second-instance', (event, argv, cwd) => {
  app.quit()
})
app.on('ready', function () {
  .....
```

Here's a full example:
https://github.com/nikolaiwarner/cabal-desktop-mini/blob/master/src/main/index.js

**Comment by karissa** [comment]
K I downgraded electron so this should be fixed again for the time being
