### ISSUE TITLE
flatmap-stream dependency no longer in npm registry

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#109]
Getting this error when trying to build locally with `npm install`:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz
npm ERR! 404
npm ERR! 404  'flatmap-stream@0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cabal-desktop'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Note: I'm getting this build error while I have the `appSettingsScreen` branch checked out.

**Comment by todrobbins** [comment]
Ah, see for context: hugeglass/flatmap-stream/issues/2

**Comment by nikolaiwarner** [comment]
@todrobbins is this still an issue for you?

**Comment by todrobbins** [comment]
I'm not seeing it anymore so 🤷🏻‍♂️✅

**Comment by TheShermanTanker** [comment]
For anyone that needs a Tl;Dr, flatmap-stream is an obfuscated and malicious module intended to steal bitcoins and avoids detection by pretending to be an average dependency, that's the reason it was removed
