### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#11]
It would be nice to have desktop notifications about new messages when the app is in the background. 

I imagine a user would want to only get notifications for the currently selected channel. 

Also, we should include a settings screen to let users disable this feature. 😂

**Comment by nikolaiwarner** [comment]
I have a working implementation of this going but I wanted to feel it out if this is a desirable feature.

**Comment by karissa** [comment]
Yeah that'd be great! Could include the option in the menubar for now, might be easier to implement than in a settings view, but that's up to you (if you feel more comfortable writing js/css/html over learning the electron api for menus..)
