### ISSUE TITLE
All unread channel badges disappear when changing channels

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-desktop#118]
When I open cabal-desktop and there's a lot of new content, there will be purple badges on several of the channels.

As soon as I change to a different channel, all of the badges go away on all the channels.

(v2.0.0)

**Comment by nikolaiwarner** [comment]
I'll take a look!

**Comment by todrobbins** [comment]
@nikolaiwarner this would be another good bug to squish soon.

**Comment by cblgh** [comment]
This might probably be fixed through the cabal-client work me and lykkin started on this week!
