### ISSUE TITLE
Could Cabal work in Beaker?

### ISSUE THREAD

**Issue by DaniellMesquita** [cabal-club/cabal-desktop#127]

**Comment by karissa** [comment]
There are people actively working on this, stay tuned!

**Comment by DaniellMesquita** [comment]
@karissa
Which things Cabal haves that doesn't works on Beaker, or the browser itself is missing features? Does it relates to UnwalledGarden API?

**Comment by cblgh** [comment]
@DaniellMesquita it relates to using hypercores, which bealer doesn't yet support. But it looks like hypercore support might be in the pipeline

**Comment by todrobbins** [comment]
Closing this issue until hypercores land in Beaker
