### ISSUE TITLE
[Feature] Support to offline messages

### ISSUE THREAD

**Issue by DaniellMesquita** [cabal-club/cabal-desktop#128]
This feature relates to private messages between users.
A single user can't seed all new messages. Users haves all new messages distributed between them into chunks.
After some time threshold (or when they are visualized and seeded), these messages are removed from new messages index.

**Comment by cblgh** [comment]
@DaniellMesquita hey, it's not really clear what you're proposing with this issue

feel free to re-open it after you've clarified what you want and why!
