### ISSUE TITLE
Upgrade to cabal-core@6

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-desktop#136]
Hello! cabal-core@6 picks up a breaking protocol change in multifeed replication, which makes cabal-core@6 peers incompatible with previous versions. I'm upgrading cabal-cli now (+ major version bump). If desktop (and mini) are upgraded too, they'll all still be able to communicate OK.

cc @nickwarner

**Comment by noffle** [comment]
oops @nikolaiwarner

**Comment by cblgh** [comment]
closed in https://github.com/cabal-club/cabal-desktop/pull/137

by the fire god @nikolaiwarner 🔥
