### ISSUE TITLE
initial 'sync' very slow or stuck with current 3.0.0 release; but, bump to electron 5 seems to fix

### ISSUE THREAD

**Issue by dwblair** [cabal-club/cabal-desktop#139]
Hi All!

I've been installing cabal desktop 3.0.0 on multiple computers, and something I just noticed is that the current release seems to 'choke' on the public cabal.  I get stuck for a long time (forever? haven't waited long enough?) on:

![cabal_freeze](https://user-images.githubusercontent.com/639760/61174971-c8cac780-a575-11e9-93b7-e8f375737b1f.png)

... but when I compile the version in the 'bump-electron' branch (which uses Electron 5) and use it, I don't get stuck!  It starts syncing immediately and very nicely.  

(In other words:  nice work @nikolaiwarner on the electron 5 bump!)

Operating system is Xubuntu. 

Might be an argument for switching over to Electron 5 in a new release soon?

**Comment by nikolaiwarner** [comment]
Interesting! Thanks so much for all of your testing!! I hope electron 5 really solves it! Let's keep an eye on it. Just merged #115 which includes the electron 5 update so we can do a new release soon.
