### ISSUE TITLE
Search content of stored cabal messages

### ISSUE THREAD

**Issue by dwblair** [cabal-club/cabal-desktop#143]
Just realizing that this could be nice, now that the public cabal has so much fun content in it! For larger cabals like that, it would be neat to be able to search for previous content.  Not a big priority, just putting it out there b/c y'all are such wizards I imagine it's somehow easy for you to do :)

**Comment by cblgh** [comment]
yes definitely! I have this in a private todo haha

i was thinking a simpler search should be the default, and then we can maybe have a more advanced search with a [greplike](https://en.wikipedia.org/wiki/Grep) syntax  (there's gotta be a module for this that we can just pop in)

**Comment by dwblair** [comment]
Oooooh greplike syntax! How fun!

**Comment by karissa** [comment]
The content might already be greppable, if it's in a single hypercore data file

**Comment by cblgh** [comment]
it is! i do it often when debugging :3 

i just want to implement some programmatic way of doing it cross-platform, from inside the interface of e.g. `cabal-cli` or even desktop

**Comment by cblgh** [comment]
we've got this as of cabal-club/cabal-client#65!
