### ISSUE TITLE
New install of cabal-desktop seem unable to parse previous database

### ISSUE THREAD

**Issue by dwblair** [cabal-club/cabal-desktop#147]
HI!

This is in XUbuntu 18.04 -- when I pull the latest version of cabal-desktop from the repo and install it (which I do often because the developers are constantly improving it and adding new awesomeness!) and restart, cabal-desktop often seems to freeze with a blank startup window. This seems to happen across e.g. minor upgrades of cabal-core that aren't protocol-breaking (I think).   If I delete the .cabal-desktop folder and start anew, things work beautifully.  Sorry I don't have more details on this fail, I'll try it again soon and see if I can learn more. 

Cheerio and thanks!
Don

**Comment by okdistribute** [comment]
Hey @dwblair, this is likely common as cabal is still in a state of active development and there have been major breaking changes to the core library from time to time. 

It'd be great to have migration pathways between versions, ideally, but it would require quite a bit of extra work and it doesn't always get done. Would be cool to have contributors on that kind of thing though!
