### ISSUE TITLE
Add key combos for navigating between cabals

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#149]
In addition to navigating between channels (thanks @nikolaiwarner!), we could add `cmd/ctrl+1`, `cmd/ctrl+2`, `cmd/ctrl+3`, etc... for selecting cabal's along the sidebar, this might also benefit from addressing/implementing suggestions in #64.

**Comment by nikolaiwarner** [comment]
+1

**Comment by todrobbins** [comment]
Would `cmd/ctrtl+n` and ``cmd/ctrtl+p` also make sense to folks?

**Comment by todrobbins** [comment]
Thanks @khubo!
