### ISSUE TITLE
Implement emojis ❤️

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#15]
This is a critical feature. 

On desktop, it's not always easy to type emojis. We should implement an emoji picker. This one seems nice: https://github.com/missive/emoji-mart

Also, we should consider the inline keyword emoji that github/slack provide .... like this :emoji: ... as that's a handy way to type emoji as well.

**Comment by callil** [comment]
branch! pls test https://github.com/cabal-club/cabal-desktop/tree/emojis @nikolaiwarner @simbolo
