### ISSUE TITLE
Update to latest cabal-client

### ISSUE THREAD

**Issue by okdistribute** [cabal-club/cabal-desktop#168]
Cabal-client has somehow introduced some breaking changes and the desktop app doesn't know how to parse and display messages anymore

Seems like we need a refactor to remove the dependency on cabal-core directly and use cabal-client instead.

Might be a nice opportunity to use to refactor the frontend here so that it is modular, perhaps `cabal-react-ui`, that removes all dependency on electron and can be used in the browser.

**Comment by nikolaiwarner** [comment]
Yessss! @okdistribute I started implementing cabal-client into Desktop maybe over a month ago but found myself distracted with other things. I should open that up again and see where I left off!

Speaking of freeing the UI from electron, I started this repo as a chance to work with react storybooks: https://github.com/cabal-club/cabal-ui/tree/initial/react ... `npm run storybook` on that and you can see how cool it is! 

I have almost all of the ui from desktop refactored into individual components that we can use for browser or electron. Where I left of with that was implementing redux. Again, the demands of raising a flock of children pulled me away. :D But once we have that, then we'd have a fully working independent, sharable UI.

Here's what i was thinking as far as steps:
- [ ] implement cabal-client into Desktop as is (just to get it working again)
- [ ] refactor the electron backend, move cabal-client there, and separate the frontend from the backend like in cabal-desktop-mini and @fenwick67's [cabal-clone](https://github.com/fenwick67/cabal-clone) (we may even want to switch to use cabal-clone's electron backend)
- [ ] finish cabal-ui and refactor react components
- [ ] use shared components from cabal-ui for a cabal-browser client
- [ ] dark mode

**Comment by fenwick67** [comment]
Heads up on cabal-clone's RPC stuff, tl;dr it's not ideal and you should probably avoid it. 

Here's the story:

The original plan was that I would make this build an Electron app and a Cordova app. So, I wrote an RPC abstraction that would (theoretically) use electron-rpc on desktop and cordova's RPC stuff on mobile, with the same frontend code. But that never came to fruition. I struggled to get nodejs to work with Cordova, and ultimately the UI would need to be rewritten for mobile anyway. So I gave up on that goal.

Thus, I originally ran cabal in the "main" process and proxied stuff to that. But the messaging overhead was too high and the benefits (not locking the UI thread) were not worth it. So I moved the actual `Cabal` out of the main process and into the renderer process (calls were still proxied through the RPC framework, but everything is just function calls).

It's more of an artifact than anything, and I am working on removing it.

**Comment by okdistribute** [comment]
@fenwick67 Regarding mobile, yes Cordova is a crapshoot. However, the Mapeo team has had great success in using both RPC and http server for cross-process communication inside nodejs-mobile. https://github.com/digidem/mapeo-mobile. Still not a super easy toolchain to work with, but definitely possible and worth the bit of elbow grease. This code is being deployed and used by real folks today, and they got it to a stable state so it's definitely possible with Cabal too!

@nikolaiwarner great work! I hadn't realized that you already almost fully finished pulling the stuff out, that's great. Separating main and renderer threads are crucial to not block the user interaction. Since we are in javascript world, rather than CLI world, we have slightly different concerns. I wonder if we could implement a middleware layer between cabal-client and cabal-ui-react that would be flexible as to the implementation (http, websocket, electron-rpc etc)? Then I think we also wouldn't need Redux anymore -- because redux is essentially that RPC layer already.

**Comment by fenwick67** [comment]
@okdistribute To clarify, I didn't mean to say RPC was a bad idea for a Cabal app, just that *my code* was bad.

**Comment by okdistribute** [comment]
RPC is great. Redux plus RPC might be overkill though!

**Comment by nikolaiwarner** [comment]
Implemented in https://github.com/cabal-club/cabal-desktop/pull/186 🎉
