### ISSUE TITLE
Any plan to add it to AUR?

### ISSUE THREAD

**Issue by tiotrom** [cabal-club/cabal-desktop#171]
Would be great to see an AUR package for this. Cheers!

**Comment by cblgh** [comment]
@tiotrom i have no idea how to do that, but feel free if you want to champion that ^_^!

**Comment by tiotrom** [comment]
We will do it!

**Comment by tiotrom** [comment]
There you go https://aur.archlinux.org/packages/cabal-desktop-git/ ;)

**Comment by cblgh** [comment]
@tiotrom thank you so much!! y'all are the best :3

**Comment by cblgh** [comment]
closing this now as it's accomplished

**Comment by cblgh** [comment]
@tiotrom does the AUR repo update automatically when we push new releases? cause we just released a major version of cabal desktop and a friend just inquired about the AUR package :~

**Comment by tiotrom** [comment]
We keep an eye on this github and update the AUR when there is a new release from you guys.

**Comment by cblgh** [comment]
ah great to know, thanks again @tiotrom ^_^

**Comment by tiotrom** [comment]
Hey guys. We are unable to support the AUR version of this package anymore (unfortunately we are too busy). Are you able to help with that? https://aur.archlinux.org/packages/cabal-desktop-git/ Let us know, if you can't we will strive to maintain it but we can't promise. Cheers!

**Comment by nikolaiwarner** [comment]
Hi @tiotrom ! No worries! In general Cabal Desktop is still a work in progress and not ready for primetime anyway. I think once it's more mature we can attempt to support builds for more platforms.

**Comment by tiotrom** [comment]
Great! In the meantime if we can help keep the AUR package updated we will.
