### ISSUE TITLE
Use redux-toolkit for pretty redux 

### ISSUE THREAD

**Issue by khubo** [cabal-club/cabal-desktop#196]
use [redux-toolkit](https://redux-toolkit.js.org/) for pretty code.

**Comment by cblgh** [comment]
@khubo i was having a peek in [reducers.js](https://github.com/cabal-club/cabal-desktop/blob/master/app/reducer.js) and noticed we were using redux-toolkit! does that mean this issue can be closed, or were there additional redux-toolkit improvements you had in mind? :3

**Comment by khubo** [comment]
@cblgh yeah, I think its okay to close this one
