### ISSUE TITLE
Add option to leave channel

### ISSUE THREAD

**Issue by khubo** [cabal-club/cabal-desktop#198]

**Comment by cblgh** [comment]
unjoin -> leave : 3

**Comment by nikolaiwarner** [comment]
Implemented in https://github.com/cabal-club/cabal-desktop/pull/186 💫

Current mvp UI for leaving a channel:
<img width="594" alt="Screen Shot 2020-01-27 at 10 30 04 PM" src="https://user-images.githubusercontent.com/40796/73233482-b2244080-4154-11ea-9fd8-3066b42dd285.png">
