### ISSUE TITLE
Add a UI to list channel members

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#203]
This probably could be a pane that opens from the right, listing each member who has joined the active channel and showing if they are online.

bonus: since it's not relevant on the channel level, move the peer connected count to the sidebar on the the peer list

from here:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/40796/73234139-e993ec80-4156-11ea-8d11-4f3b4ba0c489.png">
to here:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/40796/73234285-60c98080-4157-11ea-931a-ec88d9612f57.png">

**Comment by khubo** [comment]
this [PR](https://github.com/cabal-club/cabal-desktop/pull/204) should move the connected peer count from top to the sidebar.  prolly it needs some wording/style modifications?
