### ISSUE TITLE
cabal alias is clipped when emoji/capitals are present

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#205]
![Screen Shot 2020-01-28 at 11 46 37 AM](https://user-images.githubusercontent.com/158590/73295050-2e09a180-41c4-11ea-8243-8967af871583.png)

I'll get to this one, but wanted to document it before I forgot.

**Comment by cblgh** [comment]
emoji cabal aliases is pretty dope for the desktop innit, i love the tiny sidebar icons haha

**Comment by todrobbins** [comment]
Closing since this appears to be fixed with the new UI/font updates in 5.0.5

<img width="219" alt="Screen Shot 2020-05-20 at 9 35 06 PM" src="https://user-images.githubusercontent.com/158590/82520616-ddef7b80-9ae1-11ea-9e5d-c66f1305a6ed.png">
