### ISSUE TITLE
4.1.0 Release

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#213]
This issue is for collecting all and any last issues that should be solved before the next public release build. Please add any comments and ideas for things that must be fixed before we ship the next release. <3

Todo for release:
- [x] unread counts for channels not resetting immediately when switching to channel - [fix](https://github.com/cabal-club/cabal-desktop/pull/215)
- [x] #209 - throttle desktop notifications
- [x] settings (like cabal name, notification preferences) for a cabal sometimes dont persist between restarts - fixed by #218
- [x] update changelog
- [ ] fix release build issue with build.js in index.html

**Comment by cblgh** [comment]
* [ ] on startup the ui loads, then goes white, and then loads again
* [ ] when clicking around channels between various, sometimes the channel i have loaded has the content from `default` (or another previously loaded channel?) loaded into it 
* [ ] `cabal-dev` channel in the public cabal, iirc, has content that causes the ui to grow a horizontal scrollbar (unsure what cause it atm)
* [ ] hovering over channels and other actions seem slower than the 4.0.0 release build. (might just be because i am running a non-built version)

**Comment by khubo** [comment]
@cblgh this [PR](https://github.com/cabal-club/cabal-desktop/pull/211/files) should have fixed the second one. 
@nikolaiwarner  what do you think will be a good fix for #209 ?

**Comment by nikolaiwarner** [comment]
the inital startup reload is a side effect from `electron-reload` for reloading the app during code changes in development. its annoying for dev but wont happen in production builds. lemme know if im wrong

**Comment by nikolaiwarner** [comment]
im thinking the slow in the ui may be from cabal-client et al living in the render process. gonna be time soon to split those up. all cabal stuff in the main process and just react in the render

**Comment by khubo** [comment]
[] removing and adding the same cabal throws an error

**Comment by nikolaiwarner** [comment]
@khubo my guess is that's related to this issue: https://github.com/cabal-club/cabal-client/issues/12

**Comment by cblgh** [comment]
this is looking really good y'all! i've just tried it out a bit :33

i ran into one weird bug though. i have a few cabals: the public cabal, an old cabal from before, and then one i created just now. when i toggled back and forth from the new cabal and the public cabal, eventually the new cabal's message in the default channel would override the backlog of the public cabal (when i switched to that). if i click any channel in the public cabal, e.g. default again, then the history is correctly loaded.

the topic of the public cabal is set correctly though.

i could replicate it by: 
* restarting cabal desktop
* creating a new cabal
* posting a message in the new cabal
* clicking back and forth between the new cabal and the public cabal until the new cabal's message is displayed in the public cabal

it's pretty minor though and this last time i replicated it, it disappeared after a few seconds

**Comment by khubo** [comment]
@cblgh the issue is that we fetch many of our data from focused cabal.. while updating we were not switching the default one in client lib.
this [PR](https://github.com/cabal-club/cabal-desktop/pull/217) should fix it.

**Comment by nikolaiwarner** [comment]
ok i fixed the save file corruption issue: https://github.com/cabal-club/cabal-desktop/pull/218

that was the last blocker in my book for this release

**Comment by cblgh** [comment]
💪 💪 💪 💪 💪 reviewing!

**Comment by nikolaiwarner** [comment]
whoops this is actually the 4.1.0 release 🤗

**Comment by cblgh** [comment]
closed cause released :~
