### ISSUE TITLE
4.1.0 binary release?

### ISSUE THREAD

**Issue by svdo** [cabal-club/cabal-desktop#226]
Hi! Thanks for all the work you're doing on Cabal, much appreciated! Today I noticed that 4.1.0 was out and I wanted to download the binaries, but they are not there in the release on GitHub (https://github.com/cabal-club/cabal-desktop/releases/tag/v4.1.0). My colleague says he did download them there recently. Did they accidentally get removed maybe?

**Comment by nikolaiwarner** [comment]
Thanks @svdo! There was an issue with the build process that produced those binaries that resulted in some of the binaries not working. I'll have a new set of builds up soon. Keep an eye out for 4.1.1 and I'll update this issue once they're up!

**Comment by nikolaiwarner** [comment]
@svdo Ok, check out this new release: https://github.com/cabal-club/cabal-desktop/releases/tag/v4.1.1 ... please let me know how it goes!

**Comment by svdo** [comment]
@nikolaiwarner Up and running, thanks!!!
