### ISSUE TITLE
5.0.0-prerelease empty screen

### ISSUE THREAD

**Issue by markspanbroek** [cabal-club/cabal-desktop#228]
Running the 5.0.0-prerelease on MacOS gives an empty white screen. The developer tools show an error in finding the module 'debug'.

<img width="982" alt="Screen Shot 2020-03-24 at 09 56 20" src="https://user-images.githubusercontent.com/1766771/77407144-fda24600-6db5-11ea-8f67-dafeced98d7f.png">

**Comment by nikolaiwarner** [comment]
@markspanbroek thanks for catching that! def something is up with the release process. i'll take a look!

**Comment by markspanbroek** [comment]
Fixed with the 5.0.0 release.
