### ISSUE TITLE
Allow page zooming

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-desktop#23]
The default font is too small for me to read.  I'd like to zoom the page using cmd-plus and cmd-minus.

From [this issue](https://github.com/electron/electron/issues/8793) in the electron repo I infer that this normally works by default, and I don't see any code in Cabal Desktop to change the zoom behavior, so I'm not sure why it doesn't work.

**Comment by noffle** [comment]
I increased the default font size in 81d0e13c2cf3b3ed18687aba1d0366d12ce5d33a

![cabal](https://user-images.githubusercontent.com/489362/43924584-dfeea40a-9bd9-11e8-8dbc-baab28d37c89.png)

**Comment by nikolaiwarner** [comment]
fixed in #31
