### ISSUE TITLE
Properly stop Cabal processes on Windows 10 when exiting

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-desktop#231]
for some really strange reason, running and then exiting cabal desktop on Windows 10 does not remove the processes. It seems they go from being active to becoming backgrounded processes.

i searched around a bit on similar issues (will update this thread with the links from my other computer, if i remember :^) and SEEMINGLY we're doing everything correctly?

pernicious.

**Comment by nikolaiwarner** [comment]
fixed in the 5.1.0 release!
