### ISSUE TITLE
/join #channelname  joins the wrong channel

### ISSUE THREAD

**Issue by okdistribute** [cabal-club/cabal-desktop#233]
`/join #channelname` joins the wrong channel, it joins ##channelname, but it should be joining just #channelname. Perhaps it should detect the first `#` and remove it from the input? I also wonder if this issue exists in cabal-cli.

**Comment by cblgh** [comment]
is it just a UI thing? cause we don't have any opinion on # or no in channel names

**Comment by okdistribute** [comment]
I guess it's a UI thing? When i'm trying to join #cabal-dev, for example, its empty.. then I had to `/join cabal-dev`

**Comment by nikolaiwarner** [comment]
@okdistribute cabal-client has been updated to remove the first # in a channel name when using the join command. so `/j cabal-dev` and `/j #cabal-dev` both will take you to `cabal-dev` on cli and desktop.
