### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by vdmokstati** [cabal-club/cabal-desktop#238]
noted few things:

- upon creating a new channel i couldnt post to it.
- shortly after i restarted and ui with all screens wouldn't load.

**Comment by cblgh** [comment]
@vdmokstati thanks for the issue. few things were borked in the latest release; we'll be kinda fast and sloppy for the next few weeks as part of [the moderation grant](https://opencollective.com/cabal-club/updates/cabal-x-subjective-moderation-mozilla-grant) we are doing

thank you for your patience!

**Comment by nikolaiwarner** [comment]
fixed by https://github.com/cabal-club/cabal-desktop/pull/239

**Comment by todrobbins** [comment]
@vdmokstati try downloading the new 5.0.5 release, which fixes a lot of the borked features: https://github.com/cabal-club/cabal-desktop/releases/tag/v5.0.5
