### ISSUE TITLE
Masquerading as another user by just changing username

### ISSUE THREAD

**Issue by karuppiah7890** [cabal-club/cabal-desktop#240]
I just change the username to the same username as another person and the desktop client shows me the same profile picture that they have, for me as well. Is this usual / expected? It feels a bit weird. Let me explain what I did though -

1. Joined the public chat using the CLI. Sent two messages.
2. Joined the public chat using Desktop and sent few messages.
3. Changed nick names a lot of times. Check below screenshots

In the below image, I used the same nickname `karuppiah` for both desktop and CLI. This is how it looks

<img width="1552" alt="Screen Shot 2020-05-14 at 1 29 02 PM" src="https://user-images.githubusercontent.com/12808424/81908823-60120880-95e7-11ea-9ef7-114fd859db66.png">

In the desktop client, I masqueraded as `fleeky` and you can notice how I get `fleeky`'s profile picture

<img width="1552" alt="Screen Shot 2020-05-14 at 1 29 23 PM" src="https://user-images.githubusercontent.com/12808424/81908925-859f1200-95e7-11ea-8e49-2abfe5b0fe73.png">

Then I changed my CLI client's nickname as `fleey` and this is how it looked

<img width="1552" alt="Screen Shot 2020-05-14 at 1 29 47 PM" src="https://user-images.githubusercontent.com/12808424/81909119-c1d27280-95e7-11ea-9978-db24f46e2d4c.png">

Finally I properly set my CLI client nickname as `karuppiah_cli` and desktop client nickname as `karuppiah` and this is how it looks

<img width="1552" alt="Screen Shot 2020-05-14 at 1 30 18 PM" src="https://user-images.githubusercontent.com/12808424/81909253-f5ad9800-95e7-11ea-9924-4e8f3dc03eb8.png">

I'm guessing this is a matter of identity. I'm still trying to understand how things work. I just felt it might not be fair to show the exact same profile pic even if the nickname is same, as that looks like the same person is continuing to speak, even if they are not. I think every person (user) might have some unique identity, like, in CLI I see there's a `whoami` which shows a key, so, I think the profile pic could be based on that or something?

**Comment by cblgh** [comment]
thank you for yr thorough testing and documentation @karuppiah7890! looks like we're basing the generated avatar hash on the name instead of the public key, which is what it should be using

**Comment by nikolaiwarner** [comment]
yes thanks @karuppiah7890 ! here's a pr to correct this: https://github.com/cabal-club/cabal-desktop/pull/241

**Comment by todrobbins** [comment]
corrected in #241
