### ISSUE TITLE
duplicate user names in peers list

### ISSUE THREAD

**Issue by rinchen** [cabal-club/cabal-desktop#242]
I have a bunch of private cabals that have never been published to the public. There are people that appear to be intercepting the swarm messages and joining them, but this is not what is actually happening because this does not show up on the cli. Instead, it looks like a render issue with the desktop client where when someone joins the public cabal, those users also show up as offline peers of private cabals.  I've attached some screenshots. 

<img width="319" alt="81948744-4f4d9c80-95bf-11ea-962a-22f92cc4e86d" src="https://user-images.githubusercontent.com/44416/81990468-78d8e900-95fc-11ea-89ef-50c1b79947a2.png">
<img width="319" alt="81948747-4fe63300-95bf-11ea-9f3b-5cb3666c2647" src="https://user-images.githubusercontent.com/44416/81990472-7a0a1600-95fc-11ea-9107-37250d24eeb2.png">

**Comment by todrobbins** [comment]
@nikolaiwarner @khubo is this related at all to #253?

**Comment by nikolaiwarner** [comment]
I think this was solved in https://github.com/cabal-club/cabal-desktop/pull/239

**Comment by todrobbins** [comment]
@rinchen could you try out the [5.0.5 release](https://github.com/cabal-club/cabal-desktop/releases/tag/v5.0.5) and verify if this is still an issue?

**Comment by rinchen** [comment]
5.0.5 fails to load resulting in an error. There is no "allow" in the security center nor a pop-up.

<img width="117" alt="Screen Shot 2020-05-20 at 23 29 01 " src="https://user-images.githubusercontent.com/44416/82526706-db951d80-9af1-11ea-9838-72613bb9c9a8.png">
<img width="542" alt="Screen Shot 2020-05-20 at 23 29 35 " src="https://user-images.githubusercontent.com/44416/82526708-dc2db400-9af1-11ea-9784-e91da29d7755.png">

**Comment by todrobbins** [comment]
Ah yes, I ran into this issue as well. Delete the `Cabal.app` from your `Applications` folder and then copy a fresh app into the folder.

**Comment by rinchen** [comment]
@todrobbins that worked. It's running now.

**Comment by cblgh** [comment]
@rinchen yay!

@todrobbins thanks for yr help  🖤  ^_^
