### ISSUE TITLE
initial launch has dev console visible

### ISSUE THREAD

**Issue by masukomi** [cabal-club/cabal-desktop#25]
### Expected behavior:
Initial launch should not have the dev console open. 

### Actual behavior:
dev console _is_ open and fills most of the window upon initial launch

### Reproduction

following the install instructions: 

```
$ git clone https://github.com/cabal-club/cabal-desktop
$ cd cabal-desktop

$ npm install             # install dependencies
$ npm run build           # build assets
$ npm start               # start the application
```

results in this.

<img width="800" alt="cabal" src="https://user-images.githubusercontent.com/2829/43921993-5ead650e-9beb-11e8-82cc-312927757213.png">

closing the developer console results in what i assume is the expected ui

<img width="800" alt="cabal" src="https://user-images.githubusercontent.com/2829/43922039-83d1c3ca-9beb-11e8-90d3-6f34ced5bda1.png">

Note that the window has not been resized after opening.

This is on macOS High Sierra

**Comment by noffle** [comment]
fixed in 4c970cb9392115b4eb43d1ea9533a1093fc2b24f
