### ISSUE TITLE
Disambiguate between users based on their public key

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-desktop#252]
In the screenshot below, I have posted messages from two identities. But since they are consecutive, and with the same nickname, they are merged. 

I think this is too easily abused. We ought to instead disambiguate when to render a new nick/message-container based on the public key (instead of the nickname)

![Screen Shot 2020-05-20 at 10 38 30](https://user-images.githubusercontent.com/3862362/82425495-dea6f400-9a86-11ea-9fe5-d8c1a2fb7f2b.png)

**Comment by cblgh** [comment]
(i mean the merging is NICE but i think it should only happen when we have some kind of mechanism for sameAs, to merge identities across machines. not like this)

**Comment by khubo** [comment]
@cblgh  its spoopy.. Will fix!
