### ISSUE TITLE
Seeding cabal archives

### ISSUE THREAD

**Issue by oelmekki** [cabal-club/cabal-desktop#254]
Hi guys,

Thanks for Cabal, it looks great!

When I build dat applications in Beaker, I usually seed friends and own data in a raspberry pi seedbox, to keep them accessible when we're offline. Is it possible to do so with Cabal? (that is, simple replication without having to launch an UI).

I tried to `dat clone dat://<cabal room key>`, but dat couldn't find it, so I'm not even sure Cabal is using it (I went through the package.json files of various cabal packages and saw some dat related stuff, but it was unclear if it was just helpers or dat itself).

Would love some guidance here (and I guess I'm not the only one interested in it, so it would be a great thing to mention in the readme).

Thanks!

**Comment by cblgh** [comment]
Yes!

You can do it according to the instructions in the cabal-cli repository:
https://github.com/cabal-club/cabal-cli#headless-mode

So, `npm install -g cabal` and then `cabal --seed <cabal key>` :)

**Comment by oelmekki** [comment]
Oh, that's awseome, thanks! (and damn, that was a fast reply, thanks for that as well ;) )

**Comment by cblgh** [comment]
;3
