### ISSUE TITLE
NixOS compatibility

### ISSUE THREAD

**Issue by Yutyo** [cabal-club/cabal-desktop#257]
There is a [PR](https://github.com/cabal-club/cabal-desktop/pull/245) about that.

**Comment by noffle** [comment]
@Yutyo Does this need to be an issue? The PR seems like enough to track this, no? Let me know if I've misunderstood & I can re-open.

**Comment by Yutyo** [comment]
@noffle in Cabal they have asked me to open that.

**Comment by Yutyo** [comment]
Now the PR is closed as well as you have closed here.

**Comment by noffle** [comment]
The PR is still showing as open for me: https://github.com/cabal-club/cabal-desktop/pull/245
