### ISSUE TITLE
'Module parse failed' running 'npm run build'

### ISSUE THREAD

**Issue by kormyen** [cabal-club/cabal-desktop#26]
![image](https://user-images.githubusercontent.com/836507/43961598-84053380-9d09-11e8-89b6-b6f7f697171f.png)

Sorry if it something broken on my end!
Just following the install steps on the repo page.

I entered:
```
$ git clone https://github.com/cabal-club/cabal-desktop
$ cd cabal-desktop
$ npm install
$ npm run build 
```

```
 ~/cabal-desktop git: master@dac13b9   !
 > npm run build

> cabal-desktop@1.0.0 build C:\Users\kor\cabal-desktop
> webpack

Hash: 57fa6d2c778024656d20
Version: webpack 3.12.0
Time: 49ms
          Asset     Size  Chunks             Chunk Names
static/build.js  2.87 kB       0  [emitted]  main
   [0] ./app/index.js 214 bytes {0} [built] [failed] [1 error]

ERROR in ./app/index.js
Module parse failed: Unexpected token (16:2)
You may need an appropriate loader to handle this file type.
|
| render(
|   <Provider store={store}>
|     <App />
|   </Provider>,
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cabal-desktop@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cabal-desktop@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kor\AppData\Roaming\npm-cache\_logs\2018-08-10T13_46_48_682Z-debug.log
```

[2018-08-10T13_46_48_682Z-debug.log](https://github.com/cabal-club/cabal-desktop/files/2278139/2018-08-10T13_46_48_682Z-debug.log)

**Comment by noffle** [comment]
What version of node are you running?

**Comment by kormyen** [comment]
v8.9.1

**Comment by kormyen** [comment]
Updated to 10.8.0 and same output =/

![image](https://user-images.githubusercontent.com/836507/44129929-11cfeb40-a09f-11e8-8c49-a7f30b4ace4b.png)
[2018-08-15T03_20_14_053Z-debug.log](https://github.com/cabal-club/cabal-desktop/files/2289100/2018-08-15T03_20_14_053Z-debug.log)

**Comment by nikolaiwarner** [comment]
This sounds like an issue related to babel at the time. Sorry we didnt follow up on this sooner!! I'm clearing out older issues. If the latest master still doesn't build for you, we can reopen this issue.
