### ISSUE TITLE
Stuck on loading screen in v6.0.2

### ISSUE THREAD

**Issue by cjdesno** [cabal-club/cabal-desktop#268]
Both in the appImage and built from source, it stays stuck on a loading screen when i start it ("loading hypercores" or whatever). v6.0.1 works fine. My node version is v13.2.0, but I assume that's not super relevant given that I see the issue in the appimage and not just when building from source.

**Comment by nikolaiwarner** [comment]
Thanks @cjdesno! The mac build seems to be working. I'll check out the appImage and see if I can reproduce.

**Comment by substack** [comment]
This also looks like what happens to me when I run the latest desktop with `npm start`: no errors in the console or in the debugger window. The screen just shows "Loading hypercores and swarming..." and gets stuck there.
