### ISSUE TITLE
Messages show up twice

### ISSUE THREAD

**Issue by FinlayDaG33k** [cabal-club/cabal-desktop#277]
Hii there,

I started using the Cabal Desktop (6.0.4 on Windows 10) just a moment ago, but interestingly enough, messages show up twice (most of the time)
![](https://i.imgur.com/9MlfIHF.png)

This "issue" however, is gone if I swap to another room, then move back:
![afbeelding](https://user-images.githubusercontent.com/13424273/90333992-ba49ad80-dfca-11ea-881d-bc133dd1ba01.png)

Though it comes back when new messages are being send/received again.

**Comment by cblgh** [comment]
@FinlayDaG33k ah, thanks for the report. really appreciate the screenshots :)

**Comment by kwadroke** [comment]
I'm seeing this in my notifications, but not on the Desktop app (via Linux Appimage).  Not sure if it's the same issue or not. I can open a new one if needed.

**Comment by okdistribute** [comment]
Yes since we haven't seen a similar report in cli I would guess its a bug in the desktop code, perhaps the renderer redux layer?

**Comment by cblgh** [comment]
oh yeah it's definitely something that's goin wonky in desktop. i looked at it a bit but still working out how desktop (and react, redux - lol) does things

so far i could consistently replicate it by typing two messages quickly after each other. there's also an error/warning message that's triggered in the dev console about duplicate keys. kinda feels like it might be the debouncing/throttling somehow, but i am not sure

**Comment by timgoeller** [comment]
Had the same issue, though in my case the message seemed to duplicate endlessly. However the duplicates disappeared after a restart of cabal.

**Comment by Gronis** [comment]
I've noticed that this bug also adds duplicate messages to other cabal threads that you are not currently viewing. For example, I can have like 5 unread messages (according to the notification badge next to the cabal channel in the UI), but in reality, its like 3 messages.

**Comment by cblgh** [comment]
looking like we have a fix in [cabal-desktop@6.0.8](https://github.com/cabal-club/cabal-desktop/releases/tag/untagged-5d7811ec28130004a9a5) (a draft release atm)

@Gronis @FinlayDaG33k @timgoeller any of you up for trying out the draft release & seeing if the issue has been fixed for y'all? :)

**Comment by FinlayDaG33k** [comment]
I was just about to hit the clouds (go to bed) so I'll test it out tomorrow :)

**Comment by Gronis** [comment]
Same for me :)

**Comment by nikolaiwarner** [comment]
I went ahead an published the release. You can check it out here: https://github.com/cabal-club/cabal-desktop/releases/tag/v6.0.8

I think the unread message count is still counting the duplicates so we'll have to get that one on the next release. But at least duplicate messages are not being shown now!

**Comment by FinlayDaG33k** [comment]
Can confirm that it doesn't show duplicate messages anymore.

**Comment by cblgh** [comment]
Thanks for the confirmation—and the initial issue; it’s been very helpful for gathering info, having something to point people to & ultimately for mitigating the problem :3

**Comment by FinlayDaG33k** [comment]
Considering this issue is now solved, I'll be closing it :)
