### ISSUE TITLE
More URI handling/rendering support?

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#284]
I noticed a couple of URI schemes we might add handler support for within the [Dat](https://dat.foundation/explore/projects/) family:

- `hypergraph://`
- `hypermerge://`

Here's how they currently render in light and dark mode:

<img width="864" alt="Screen Shot 2020-09-14 at 1 14 25 PM" src="https://user-images.githubusercontent.com/158590/93144191-b3d05380-f6a6-11ea-8d9d-c668a897c524.png">

<img width="860" alt="Screen Shot 2020-09-14 at 1 14 49 PM" src="https://user-images.githubusercontent.com/158590/93144199-b6cb4400-f6a6-11ea-8397-bce468ce7aed.png">

It seems like the app is picking up the hash in `hypergraph://` URIs in the dark mode 🤷🏻

**Comment by leeclarke** [comment]
I can add those in!

**Comment by leeclarke** [comment]
@todrobbins Follow up question,    what app open hypergraph and hypermerge ? I want to test but not sure what to install to open them. 

BTW thanks for that bug on the dark mode link, thanks! 😄

**Comment by todrobbins** [comment]
I responded in Cabal, but here you go:

Hypergraph apps:

- https://github.com/hypergraph-xyz/cli
- https://github.com/hypergraph-xyz/desktop

Hypermerge apps:

- https://github.com/automerge/pushpin
- https://github.com/automerge/trellis

**Comment by leeclarke** [comment]
Thanks Tod. never hurts to post in multiple locations :)

**Comment by cblgh** [comment]
added in #285—thanks @leeclarke!! :3
