### ISSUE TITLE
Package into apps and make releases

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-desktop#29]
I don't know anything about this yet, but these tools could help:

"Run a single command to turn your app into binaries for macOS, Windows, and Linux - for all supported architectures."
https://electronforge.io/

"A complete solution to package and build a ready for distribution Electron app for macOS, Windows and Linux with “auto update” support out of the box."
https://www.electron.build/

Todo:
- [x] add icons
- [x] add mac config
- [x] add windows build configuration
- [x] add Linux build configuration
- [x] put downloadable releases on GitHub
- [ ] bonus: automate this process?

**Comment by cblgh** [comment]
yeah i just ran into this experimentally today when i had to install brew
and npm to get it running on a friend's computer.

in the past i used electron-packager with these commands
https://github.com/cblgh/rotonde-choo/blob/master/package.json#L7-L11

**Comment by noffle** [comment]
@mixmix suggested electron-builder, which they use for patchbay: https://github.com/ssbc/patchbay-builder

**Comment by mixmix** [comment]
electron-builder has been a dream so far.
If you need a hand I'd be happy to have a go setting something up and basically copying in the details needed for cabal, on the off-chance it's as simple as that. TBH the trickiest part was getting icon files sorted for all the OS (gods why does it suck so much)

**Comment by callil** [comment]
@nikolaiwarner any more details about what has to be done to post releases? would we also want a mechanism to notify people of new versions?

**Comment by nikolaiwarner** [comment]
@callil I'll need to check, but i think the process is: when we decide it's time for a release, someone manually runs the build scripts, then takes the builds and drops them into the github release form. Not hard... but very manual.

I think showing a little indicator or banner that a new release is available is a pretty good idea.... and ok compromise from not doing a full on automatic update thing. There's probably a simple github api to check for releases.

**Comment by mixmix** [comment]
You can add a github token to automate the upload part I think. I've not
bothered with this sofar.

You need someone with a mac developer license for the mac build - if you
have one electron-builder will sign the build, otherwise it won't work

**Comment by noffle** [comment]
@mixmix oof, are mac dev licenses mandatory now on mac? You used to be able to set something in system settings to have it let you run "untrusted apps".

**Comment by nikolaiwarner** [comment]
@noffle I think the "untrusted apps" option is an option still.... I try it out and see. I have a dev license if not.

**Comment by mixmix** [comment]
Yeah i dunno, I think the current installers I make are untrusted, I think
there's an extra level of hoop jumping required for users using unsigned
apps as they're "double untrustworthy". I would recommend signing if
someone on team can

**Comment by nikolaiwarner** [comment]
✅
