### ISSUE TITLE
mac zip file has invalid permissions

### ISSUE THREAD

**Issue by balupton** [cabal-club/cabal-desktop#304]
the .app from [Cabal-6.0.6-mac.zip](https://github.com/cabal-club/cabal-desktop/releases/download/v6.0.6/Cabal-6.0.6-mac.zip) results in:

<img width="372" alt="Screen Shot 2021-01-29 at 6 09 24 pm" src="https://user-images.githubusercontent.com/61148/106243274-32481f00-625d-11eb-923c-34d8e261e156.png">

will try the [.dmg](https://github.com/cabal-club/cabal-desktop/releases/download/v6.0.6/cabal-desktop-6.0.6-mac.dmg) later

**Comment by dualhammers** [comment]
I have the same issue.
