### ISSUE TITLE
Browser version?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [cabal-club/cabal-desktop#323]
If this is JavaScript - this is mean that it can works inside web browser?

**Comment by ralphtheninja** [comment]
In theory yes, but you need a server so the browser can find peers, which isn't needed with `cabal-desktop` since it can connect to a `hyperswarm` without any server.

**Comment by vitaly-zdanevich** [comment]
> but you need a server

Service worker?

**Comment by ralphtheninja** [comment]
> Service worker?

A websocket server or similar running e.g. `hyperswarm-web`.

**Comment by vitaly-zdanevich** [comment]
In browser you can use WebSockets.

Browser version is more secure because of the sandbox, this is more dangerous to install dedicated software.

**Comment by dorkmo** [comment]
would browser work on smart phone?
