### ISSUE TITLE
Proposal Android version

### ISSUE THREAD

**Issue by Pantyhose-X** [cabal-club/cabal-desktop#328]
Rust 100%
Maybe we can write it in [Rust language](https://github.com/cabal-club/cabin) and use [Dioxus](https://dioxuslabs.com/) for user interfaces

**Comment by cblgh** [comment]
thanks for the idea @Pantyhose-X :) I'll ping you again once we have a stable rust core of cabal running and maybe you can have a look around & play with things? :>
