### ISSUE TITLE
Implement favorite/starred/pinned channels

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#33]
In the sidebar, provide a UI for setting channels as "favorites". This should keep the channel pinned to the top of the list of channels.

**Comment by noffle** [comment]
What does this mean?

**Comment by nikolaiwarner** [comment]
This would be a feature that lets a user choose certain channels to be listed above all the other channels in the sidebar.... because the probably interact with those the most perhaps

**Comment by nikolaiwarner** [comment]
@cblgh is this a feature you'd like to provide with cabal-client? or should we go ahead and implement fully in Desktop? the concept here is that this is in addition to joining but also marking channels for yourself that you really like them and giving them visual priority in the UI

**Comment by cblgh** [comment]
@nikolaiwarner go ahead and implement fully in desktop for now! 

if we want to, we can always add it after we release the first version ^_^
