### ISSUE TITLE
[Feature request] Create Thread

### ISSUE THREAD

**Issue by Pantyhose-X** [cabal-club/cabal-desktop#331]
Allow users to Liberty Create Thread
Thread time, for 1 year. or forever
Only groups, administrators and creators, can Remove Thread channels
![](https://support.discord.com/hc/article_attachments/4405086336279/threads_demo_gif.gif)
Cabal can feel like an ocean sometimes with walls of Image, Video, text rapidly flooding your screen. Interesting conversations can be confusing to follow in the middle of other conversations and may just disappear entirely.

### Example structure
```
# cabal-dev
  * cabal-Announcements
  * cabal-Translator
  * cabal-videos
  * cabal-Image
  * cabal-bot
  ```

**Comment by cblgh** [comment]
we don't even have images atm so this issue doesn't make a lot of sense; almost has a spamlike quality

**Comment by Pantyhose-X** [comment]
If the future cabal has no images and videos, cabal has no meaning; cabal is a kind of garbage
