### ISSUE TITLE
Allow multi-line input in textbox

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-desktop#38]
It's not simple to make a textbox that allows multi-line input and expands as you type.  Maybe using content-editable, though that has its own quirks related to different browsers, rich copy-paste, etc

Also make shift-enter add a newline instead of sending the message.

**Comment by callil** [comment]
check out https://github.com/cabal-club/cabal-desktop/tree/pr/38 for initial stab at this

**Comment by callil** [comment]
completed in #42
