### ISSUE TITLE
fix timestamps being displayed as NaNs

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-desktop#4]
i patched cabal-desktop to use the latest db schema of `cabal-node`

but when i got messages displaying again the timestamps were being displayed as NaN instead of the actual timestamp of the entry. i looked around and tried various fixes but ultimately couldn't figure it out

@karissa am i missing something super obvious in cabal-desktop? first time playing around with react/redux code so i'm probably misunderstanding a lot

**Comment by karissa** [comment]
the cabal-desktop code is likely doing timestamps improperly !

**Comment by karissa** [comment]
fixed!

**Comment by cblgh** [comment]
yaaaaaaay!
