### ISSUE TITLE
Can't join previously created / shared cabals

### ISSUE THREAD

**Issue by KidkArolis** [cabal-club/cabal-desktop#55]
Getting this when trying to join:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/324440/44225784-4c254280-a186-11e8-8b91-f1cdae7611d6.png">

**Comment by callil** [comment]
related to #52 ?

**Comment by KidkArolis** [comment]
Easy to reproduce on @599fe5c1b49ec98144cf9c5fd2f90c5f8e601136

1. Click (+)
2. Create new cabal
3. Say "hello"
4. Click "share cabal"
5. Close the app
6. Open the app
7. Click (+)
8. Paste in the link
9. Nothing happens, console has that error "cabal already exists"
