### ISSUE TITLE
implement slash commands

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-desktop#6]
`/join` `/nick` etc

can we abstract [cabal/commands.js](https://github.com/cabal-club/cabal/blob/master/commands.js) enough to reuse it between desktop and the cli?

like, i wonder if we can implement the writeLine methods for the desktop such that they both have the same api

**Comment by karissa** [comment]
fixed!

**Comment by karissa** [comment]
I don't think abstracting this out will benefit much as writeLine is entirely different based on each platform, you'd probably spend more time abstracting that out then you'd save from just implementing the tiny set of if/then statements. I just sent in a commit for this!

**Comment by cblgh** [comment]
woahhh so good!
