### ISSUE TITLE
Create a cabal-specific settings screen

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#70]
We need an interface for placing inputs for setting for various cabal-specific settings.

Examples of settings could include:
- notifications
- time format
- nick
- theme colors
- link to on disk storage
- etc

This can also serve as a place to let users opt in to experimental features as we are testing them out.

**Comment by MarkBennett** [comment]
Registering to handle `cabal:` links would make a great preference. ;)

See #74

**Comment by todrobbins** [comment]
@nikolaiwarner anything I can help with?

**Comment by nikolaiwarner** [comment]
@todrobbins oh! yes! want to make a settings screen? this is next on the list so we can start adding experimental features and have toggles for them. i think @simbolo made a design mockup in another issue that you could run with!

**Comment by nikolaiwarner** [comment]
check out the "Settings" section on this one: https://github.com/cabal-club/cabal-desktop/issues/73

**Comment by todrobbins** [comment]
I'll mostly be helpful building the markup, but at least I can do that. 😊
