### ISSUE TITLE
Move desktop notifications to a opt-in cabal setting

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#71]
Desktop notifications in cabal are still an experimental feature. Let's disable them by default and allow user to opt in to the feature from the cabal-specific settings screen.

Currently blocked by not having a settings interface. :D

**Comment by todrobbins** [comment]
per `andrew` on the public cabal:

> is there any way to turn off desktop notifications on mac os cabel client?

Current workaround in macOS is to open `System Preferences` > `Notifications` and customize notifications for Cabal there.

**Comment by dwblair** [comment]
Hi All!  I just wanted to +1 / bump this; the latest version of Cabal Desktop feels like it's working really nicely, but as someone who has the experience of reinstalling it 'from scratch' (including wiping the .cabal-desktop folder, with stored messages -- forcing an initial sync from scratch), I notice that it's quite overwhelming to have the screen filled with notifications on the initial sync of the public cabal -- which might throw new users off ...

So yes -- defaulting to 'no notifications' on initial use would be really great, if that's easy to do!

**Comment by cblgh** [comment]
+1
