### ISSUE TITLE
Proposed Cabal (Desktop) Logos

### ISSUE THREAD

**Issue by masukomi** [cabal-club/cabal-desktop#72]
## Background
The desktop app doesn't have an app icon. I wondered if cabal actually had an icon and all i found was a downward pointing arrow on cabal.chat which didn't seem to visually speak to the concept of "this is a chat app" and didn't seem to be connected to the concept of cabals. I wasn't really sure what it was trying to convey. 

So, I threw together a couple logo options that, i believe, convey "this is a chat app", work in multiple sizes I think they'd look good in an app dock / switcher and would print well in stickers and t-shirts, and be easily clickable on a phone.

Maybe we use these. Maybe they just serve as a starting point for a discussion and someone has some better idea. 

![proposed_logos](https://user-images.githubusercontent.com/2829/44304747-c1357b00-a332-11e8-982a-95aed702e2a1.png)

(original svg file here had to compress it for github to allow the upload)

[proposed_logos.svg.zip](https://github.com/cabal-club/cabal-desktop/files/2299996/proposed_logos.svg.zip)

if folks like these but would like some tweaks i'm happy to adjust.

**Comment by noffle** [comment]
Grayscale remixes:

1. ![g30](https://user-images.githubusercontent.com/489362/44304779-cb4b7f80-a31a-11e8-98b8-2dc05fd26dbe.png)
2. ![g32](https://user-images.githubusercontent.com/489362/44304782-fdf57800-a31a-11e8-9e76-4667846c59d1.png)
3. ![g31](https://user-images.githubusercontent.com/489362/44304781-e4ecc700-a31a-11e8-9c0b-be24fa78e3ce.png)

**Comment by masukomi** [comment]
I like the grayscale versions @noffle I think I also prefer the variation without the cube lines. it seemed to hint at them, when I was making it. I think in general simpler is better when dealing with logos. 

Out of the gray ones i like number 3 best, but can imagine a number of situations where you'd want to switch to 2. I think it'd be hard to come up with a single grayscale one that would be applicable in all situations. 

Are the grayscale variants because you'd like to keep the logo in greyscale, or just as another option? Personally I prefer something with color for an app icon. I'm not suggesting my colors are the "right" colors, but grayscale would feel out of place alongside all the other icons in my dock.

**Comment by masukomi** [comment]
Full disclosure: For the base of this I took an icon from The Noun Project, added a border and colors, and reworked the vector objects that made it up for easier modification. Noun Project stuff is dual licensed. CC licensed with credit unless you pay, but I pay so that credit isn't required.

I did a quick search through all the chat app icons i could find on google and I didn't see anything that looked very similar to this. So, i think we're also good with regards to it not getting confused for anything else.

**Comment by nikolaiwarner** [comment]
I would suggest avoided the chat bubble as the defining element of Cabal's identity. Taking a quick look at the hundreds of other chat platforms, I can see that the most common icon is exactly a speech bubble. Cabal is a very special kind of chat software and deserves an identity just as unique as it's capabilities.

**Comment by noffle** [comment]
@masukomi I really appreciate the time you took to design & share. I'm trying to play off the energy you're bringing and throw out some variations of my own as well. Excited to keep iterating on this. :star2:

**Comment by noffle** [comment]
![rgb](https://user-images.githubusercontent.com/489362/44306313-baae0000-a340-11e8-9089-1c89d8465393.png)

**Comment by cblgh** [comment]
so wait, the icon designed by @simbolo doesn't appear in the builds? because this PR should've added them https://github.com/cabal-club/cabal-desktop/pull/50

this is the icon, which i like a lot ![icon](https://user-images.githubusercontent.com/40796/44171694-e3b46380-a0a8-11e8-9f96-c602f64a554c.png)

**Comment by masukomi** [comment]
@cblgh it doesn't appear when i build it with 

```
npm install             # install dependencies
npm run build           # build assets
npm start               # start the application
```

but maybe i'm doing it wrong, as i'm not a node geek. 

That being said, regardless of how cool or not cool, the triangle looks it gives me no clue what i'm dealing with. One could argue that the nike swoosh doesn't give you a clue you're dealing with a shoe company (ostensibly) but they also spent millions making sure everyone knew the connection. 

The triangle doesn't work from a utility perspective. 

From a design perspective the black and white logo you posted is aggressive, maybe suggestive of "hackers" or "punks" doing nefarious things? (obviously that's a very subjective take) @noffle's color triangles don't suffer from this. The rounded corners of the hexagon and the 3d aspect help make it more approachable. 

side note: practical issues: The black with white triangle involves a gradient, which is almost imperceptible but will potentially result in issues when converted to physical media (i used to work in prepress). Also, you'd have to use a different logo on black shirts.

> each installer dynamically chose a random HSL/RGB for the icon

It's a nifty idea but i'd _strongly_ recommend against it because it's going to lead people to ask the question of "what's different about this one?" and introduce a small amount of insecurity. Now, a different color variant for desktop, vs mobile, vs terminal might work. 

re the colored triangles in a hex. the colored triangles are a huge improvement in my book. I like them a lot. I don't think the gray hex works, but i like that there's _something_ around the triangle and that that something is softened. maybe just making the hex a color?  Personally i might try rounding the corners of the triangle some if you were going to stick with it. The version with the text doesn't work for me at all. sorry. 

-----

Cabal is ultimately, competing with Slack. it doesn't matter if the developers of it are attempting to compete with Slack, the potential users are going to be trying to answer the question of "which chat app should I use?" and it's basically "Slack or x" because slack is effing huge, and free. You want a logo that's approachable, non-aggressive, and non-intimidating. Having a logo that gives you a clue what kind of app you're looking at is a big bonus. 

The slack logo fails on utility too, but it is very non-threatening, the S gives you a clue what app it's for, and the colors and the way they overlap and combine to make a new color suggests things coming together.

**Comment by masukomi** [comment]
can someone explain what the triangle is supposed to represent? what it emerged from? is it just a shape that someone liked?

**Comment by noffle** [comment]
@masukomi I think it's a Marveilles design (a group of designers & developers /w a similar aesthetic). As far as I know, it's just a pretty geometric shape.

cc @simbolo @neauoire

**Comment by neauoire** [comment]
it's just a pretty geometric shape

cc @cblgh

**Comment by gwbutler** [comment]
I was playing around with making the triangle into a logotype, which might be good for an on-boarding screen or something: 

![cabal-logo-idea](https://user-images.githubusercontent.com/40041619/44610300-98493600-a7c9-11e8-9bf3-074b8dde2a21.png)

It reminds me of an arrow on a compass, so I thought pointing one up, one down was also neat in the context of how cabal works over p2p.

**Comment by fwip** [comment]
I agree with Masukomi - the arrow is pretty, but it doesn't have anything to do with either chatting or cabals.  It looks like an icon to download something.

I do like the hexagon to remind people it's powered by Dat.

And while I'm bikeshedding, I like the idea of visually representing the peers in the icon. (Possibly circles at the 'corners' of the hexagon?) Cabal is a way to bring people together to chat, and I think it would be great if the icon could reflect one or both of those.

**Comment by cblgh** [comment]
alright so the icon is pretty geometry, as mysterious as the cabal name. which is pretty much why i chose it

let's just do what the various companies that exist today do and rebrand _later_, because this issue is honestly a big energy drain. 

so i'm going to close this issue until later, when things like the [web version](https://github.com/orgs/cabal-club/projects/1) exist, the [kappa core rewrite](https://github.com/cabal-club/cabal-core/issues/6) is done and features like [moderation controls](https://github.com/cabal-club/cabal/issues/41) are in.

no offence intended for anyone involved in the discussion! i superduper appreciate all the energy that's being channeled in and around cabal 🖤 

(p.s. @gwbutler i was thinking of that idea of the icon as a compass as well, and nice idea! :3)
