### ISSUE TITLE
Updating to kappa-core

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-desktop#78]
forking the discussion at https://github.com/cabal-club/cabal-core/issues/6#issuecomment-417937724
cc @nikolaiwarner 

### things we need to do, off the top of my head 

- [x] create a dev cabal and test it out with multiple peers & clients
- [x] create a kappa-core branch for desktop
- [x] switch the frontend to the new [kappa-core backend](https://github.com/cabal-club/cabal/tree/kappa) #79 
- [x] cut a new binary release with the kappa-core code
- [x] update the official dev cabal at all the places it's exposed [[1]](http://cabal.chat) [[2]](https://github.com/cabal-club/cabal)
- [x] write a message in the existing dev cabal and redirect people to the new versions and the new dev cabal
- [ ] switch the mobile client to the [kappa core backend](https://github.com/cabal-club/cabal-mobile/issues/29)
- [ ] investigate getting the release into [brew](https://brew.sh/)
- [ ] synchronize the release of the new binaries with a new major version of [cabal-core ](https://github.com/cabal-club/cabal-core) and the [cli client](https://github.com/cabal-club/cabal) and cabal-desktop
- [ ] [write](https://github.com/orgs/cabal-club/projects/2) new [features](https://github.com/orgs/cabal-club/projects/1) making use of the amazing [kappa architecture ](http://milinda.pathirage.org/kappa-architecture.com/) and have fun chatting!!!

what's missing? 🔎

**Comment by noffle** [comment]
Generated a new kappa cabal ("kabal") for us:
```
cabal://3ce433583266d7b2ed80e2b11fdc2f24b3643fa88e7602c6dc234f9228d25382
```

**Comment by cblgh** [comment]
I totally forgot we had to migrate the mobile app as well lol, just created an issue in [cabal-mobile](https://github.com/cabal-club/cabal-mobile/issues/29)

**Comment by todrobbins** [comment]
@noffle the kappa cabal/kabal is coming up empty for me. Are we collaborating in another cabal now?

**Comment by noffle** [comment]
@todrobbins The latest one is posted on cabal.chat -- does that not work for you? (If not, could you open an issue on the repo of the client you're using)

**Comment by todrobbins** [comment]
Oh I misread this as being a separate cabal just for kappa (core) development. Carry on!

**Comment by karissa** [comment]
this seems old

**Comment by sshyran** [comment]
Hi folks, is it possible to intubate cabal-mobile ? That is still urgent idea these days... especially 4 low end Android 4.4 device holders... especially when telcos raise fees and install regional censorship webgates...

**Comment by sshyran** [comment]
+ maybe lowdb AND/OR hyper-graph-db (with Hyperdrive and dat-storage support) integration into cabal-core 4 multiplatform resiliency improvement ?

**Comment by noffle** [comment]
@sshyran We're still very interested in cabal-mobile, though resources for developing it are currently low re: funds & volunteers.
