### ISSUE TITLE
Update cabal-desktop to use new kappa cabal-core

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-desktop#79]
o/  @nikolaiwarner 

Let me know how I can {help, guide}! The branches you want to look at are `cabal-core@refactor` and `cabal@kappa`. The APIs aren't as nice as they could be, but hopefully looking at how cabal-cli handles views from the DB will be enough to go on.

Here are some good spots to look on cabal-cli:
- neat-screen.js:153 - 200: tracking user and channel listings
- neat-screen.js:220 - 276: tracking message history

**Comment by nikolaiwarner** [comment]
Update: It's going well so far! (although i may have crashed our test kabal with some bad data :D)

todo list:
- [x] connect to db
- [x] show channels
- [x] show users, 
- [x] show messages
- [x] update on new messages
- [ ] sending messages
- [ ] show author data on messages
- [ ] set/change nick
- [ ] add channel
- [ ] update on users changed
- [ ] update on channels changed
