### ISSUE TITLE
Bumpy new user experience

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-desktop#83]
I deleted `~/.cabal-desktop` and `~/.cabal` and started fresh with the new kappa-based cabal at `cabal://3ce433583266d7b2ed80e2b11fdc2f24b3643fa88e7602c6dc234f9228d25382`.  I'm using the packaged release of cabal-desktop 1.0.3, and cabal CLI 3.0.4 on macOS 10.12.6

On first boot of cabal-desktop, nothing happens for a long time.  There are no peers listed and no indication of any activity.  My username is shown as "conspirator" though I already set it to "cinnamon" in the screen where I joined the cabal.

After 10 minutes I restarted cabal-desktop a few times, with no change.

Then I started cabal CLI.  My two cabal apps were able to see each other but nobody else.  I set my nicks in both places and saw that changed picked up on the other side.

Cabal-desktop's peer list UI doesn't seem to be refreshing properly.  It shows my command-line user as offline even though it's receiving messages from it.  If I restart the command-line user, then cabal-desktop updates the UI and shows it as online.

After an hour, I can see 4 other peers which have no names.  I haven't gotten any chat messages from the outside world yet.

I tried chatting for the first time.  I can chat back and forth between my two apps.

**Comment by nikolaiwarner** [comment]
Related cabal-core issue: https://github.com/cabal-club/cabal-core/issues/17

**Comment by fenwick67** [comment]
btw @cinnamon-bun I did see your message 
![screenshot](https://user-images.githubusercontent.com/8461973/45459690-1c9f2280-b6bf-11e8-8b9f-482091c3e362.png)

**Comment by fenwick67** [comment]
@cinnamon-bun I think your underlying issue might have been related to the fact that stuff was updated to kappa (see https://github.com/cabal-club/cabal-desktop/pull/80) and released 1.0.4 exactly as you were trying this on 1.0.3, which was pre-kappa. Maybe that's why I was able to  see your message from my 1.0.3 client on the same cabal? 🤔

**Comment by noffle** [comment]
@cinnamon-bun are these issues still true?

**Comment by cinnamon-bun** [comment]
Still happening.  Something like cabal-club/cabal-core#17 is happening to me also.

The CLI and desktop apps can't see each other on the same machine.  They both see a couple of other peers, some in common and some not, which have no names or messages.

![screen shot 2018-09-19 at 12 29 11 pm](https://user-images.githubusercontent.com/32660718/45776427-b149d900-bc07-11e8-97fa-4063d037f37d.png)

Using the latest versions, both from `master` branch:
* cabal CLI commit `6387556`
* cabal desktop commit `2c2ffd2`

Both have `cabal-core 3.0.2` in their `node_modules` after installation.

I removed `~/.cabal` and `~/.cabal-desktop`, removed `node_modules` and `package-lock.json`, and then did the usual `git pull`, `npm install`, etc.  This is the new public cabal `cabal://00794...`

**Comment by dorkmo** [comment]
is cabal working for anyone? i havent seen or heard from any peers?

**Comment by fenwick67** [comment]
I'm having replication problems too, even with local peers. 

For me, with a new cabal, it worked for a bit, then eventually stopped working after tens of messages and a few client restarts. 

When it fails, the clients can see each other but don't get any new messages from each other.  Then I spun up a DigitalOcean droplet and tried connecting from there - and I was again able to see the peers, but no messages except my own, (I also couldn't see the old messages the other two peers already replicated with each other).

**Comment by noffle** [comment]
@cinnamon-bun I can't find that cabal-desktop commit. Can you double-check that?

I can't reproduce this behaviour yet. I just had two `cabal-cli`s and a `cabal-desktop`, all latest master, running and peering on the same machine without issue.

**Comment by noffle** [comment]
@cinnamon-bun I notice your CLI sees 5 peers and your desktop sees 3. Are you running more than those 2 peers? When / how / what order do those keys show up?

**Comment by cinnamon-bun** [comment]
@noffle Ah, yes, I reported the wrong commit for cabal-desktop.  It's actually `068904e Merge pull request #87 from cabal-club/show-new-channel-in-list`

I was only running those 2 peers.  The sequence was something like
1. start cabal CLI
2. observe unnamed peers joining in a few seconds, as if from the internet
3. start cabal-desktop
4. observe more unnamed peers joining cabal-desktop -- some are the same, some different from those in cabal-CLI

My `.cabal` has 273 hypercores, and `.cabal-desktop` has 274.

Let's take this conversation over to https://github.com/cabal-club/cabal-core/issues/17 which I think is the issue here.

**Comment by karissa** [comment]
I think this is fixed
