### ISSUE TITLE
Create new channel UX

### ISSUE THREAD

**Issue by todrobbins** [cabal-club/cabal-desktop#86]
I'm running cabal 1.0.4 and nothing obvious happens when I try to create a new channel in my new cabal.

For example, I click on the `+` next to `CHANNELS` and enter the new channel name, click `Ok` and didn't notice that the channel title change at the top of the app until a few tries, not realizing you have to send an initial message before the new channel appears on the sidebar.

Is that an intentional design decision? I was a bit lost at first. To not have the channel show up in the sidebar until after an initial message is sent was confusing for me.

Is the channel not created in the database until an initial message is sent?

Thanks in advance!

**Comment by nikolaiwarner** [comment]
Hi @todrobbins! Yes, channels do not exist until there's a message in the channel. I think that's a good point that we should show the new channel in the list for the local user after they create it even before a message is sent... should be an easy one to implement.

**Comment by nikolaiwarner** [comment]
@todrobbins I just added a pr to fix this one... let me know what you think!
