### ISSUE TITLE
Can't remove cabal connections from the left pane

### ISSUE THREAD

**Issue by beingalink** [cabal-club/cabal-desktop#92]
There is only a "+" button to add cabal connections but no way to remove existing ones.

**Comment by todrobbins** [comment]
@nikolaiwarner let's solve this one.

**Comment by todrobbins** [comment]
Should you utilized sindresorhus/electron-context-menu for adding a right-click > `Remove` flow for remove the cabal in the UI?

**Comment by nikolaiwarner** [comment]
😮 

nice! ok i think that's great! then next we do a cabals list ... kinda like mini where you can see them all and see high level management of all of them... with reordering, removal, sharing, etc

**Comment by cblgh** [comment]
i like what wire does, they reveal this little arrow when you hover over a chat 

![image](https://user-images.githubusercontent.com/3862362/59411665-0f34d700-8dbc-11e9-9778-db2d479df336.png)

clicking it reveals a context menu. the same context menu which is revealed by right-clicking. it makes the entire menu _discoverable_

**Comment by martinheidegger** [comment]
You could also do it "accessible". By offering a focus on the list items and using the delete key ... (later adding a visual option)
